# -*- coding: utf-8 -*-
"""hotelbooking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17I7DuuDpqWW8AOVwS-qUJ1SoVvPb6I-m

# Importing libraries
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

"""# Loading the dataset"""

df = pd.read_csv('/content/drive/MyDrive/Data-analytics/python-hotelbookings/hotel_bookings.csv')

"""# EDA and data cleaning"""

df.head()

df.tail()

df.shape

df.info()

df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'], format= 'mixed')

df.describe(include = 'object')

for col in df.describe(include = 'object').columns:
  print(col)
  print(df[col].unique())

df.isnull().sum()

df.drop(['agent', 'company'], axis = 1, inplace = True)
df.dropna(inplace = True)

df.isnull().sum()

df.describe()

df = df[df['adr'] < 5000]

"""# Data analysis and visualizations"""

canceled_perc = df['is_canceled'].value_counts(normalize = True)
canceled_perc

plt.figure(figsize = (5, 4))
plt.title('Reservation status count')
plt.bar(['Not-canceled', 'Canceled'], df['is_canceled'].value_counts(), edgecolor = 'k', width = 0.7)
plt.show()

plt.figure(figsize = (8, 4))
ax1 = sns.countplot(x = 'hotel', hue = 'is_canceled', data = df, palette = 'Blues')
legend_labels,_ = ax1. get_legend_handles_labels()
ax1.legend(bbox_to_anchor = (1,1))
plt.title('Reservation status in different hotels', size = 20)
plt.xlabel('hotels')
plt.ylabel('no. of reservations')
plt.legend(['not_canceled', 'canceled'])
plt.show()

resort_hotel = df[df['hotel'] == 'Resort Hotel']
resort_hotel['is_canceled'].value_counts(normalize = True)

city_hotel = df[df['hotel'] == 'City Hotel']
city_hotel['is_canceled'].value_counts(normalize = True)

resort_hotel = resort_hotel.groupby('reservation_status_date')[['adr']].mean()
city_hotel = city_hotel.groupby('reservation_status_date')[['adr']].mean()

plt.figure(figsize = (20, 8))
plt.title('Average daily rate in city and resort hotel', fontsize = 30)
plt.plot(resort_hotel.index, resort_hotel['adr'], label = 'Resort Hotel')
plt.plot(city_hotel.index, city_hotel['adr'], label = 'City Hotel')
plt.legend(fontsize = 20)
plt.show()

df['month'] = df['reservation_status_date'].dt.month
plt.figure(figsize = (16, 8))
ax1 = sns.countplot(x = 'month', hue = 'is_canceled', data = df, palette = 'bright')
legend_labels,_ = ax1. get_legend_handles_labels()
ax1.legend(bbox_to_anchor=(1,1))
plt.title('Reservation status per month', size = 20)
plt.xlabel('month')
plt.ylabel('no. of reservations')
plt.legend(['not canceled', 'canceled'])
plt.show()

plt.figure(figsize = (15, 8))
plt.title('ADR per month', fontsize = 30)
sns.barplot(x = df.month, y = df.adr, data = df[df['is_canceled'] == 1].groupby('month'))

plt.show()